"""Machine-learning model training and inference."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier


class NetworkMLModel:
    """RandomForest-based classifier wrapper."""

    def __init__(self, random_state: int = 42):
        self.model = RandomForestClassifier(
            n_estimators=300,
            max_depth=12,
            min_samples_split=4,
            random_state=random_state,
        )

    def train(self, X_train, y_train) -> None:
        self.model.fit(X_train, y_train)

    def predict(self, X) -> np.ndarray:
        return self.model.predict(X)

    def predict_proba(self, X) -> np.ndarray:
        return self.model.predict_proba(X)

    def predict_single(self, row, labels: List[str]) -> Dict[str, Any]:
        prepared_row = row
        if isinstance(row, np.ndarray) and hasattr(self.model, "feature_names_in_"):
            prepared_row = pd.DataFrame(row, columns=self.model.feature_names_in_)

        pred_idx = int(self.model.predict(prepared_row)[0])
        probabilities = self.model.predict_proba(prepared_row)[0]
        confidence = float(np.max(probabilities))
        return {
            "diagnosis": labels[pred_idx],
            "confidence": confidence,
            "source": "ml",
            "explanation": "Prediction generated by RandomForest classifier.",
        }

    def save(self, path: str | Path) -> None:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(self.model, path)

    def load(self, path: str | Path) -> None:
        self.model = joblib.load(path)
